#!/bin/sh
# Install the pinned toolchain inside this directory (design sections 6.1, 8.1, 8.2).
#
#   .tools/bin/uv, .tools/bin/cloudflared   pinned in config/tools.toml, sha256-verified
#   .tools/python/                          Python from .python-version, installed by uv
#   .venv/                                  dependencies from uv.lock
#   .tools/env.sh                           environment for ./alab and `source .tools/env.sh`
#
# Nothing is written outside this directory. Safe to run again: tools that are
# already installed at the pinned version are skipped.
set -eu

ROOT=$(cd "$(dirname "$0")" && pwd -P)
TOOLS="$ROOT/.tools"
TOOLS_TOML="$ROOT/config/tools.toml"

say() { printf '==> %s\n' "$*"; }
die() { printf 'bootstrap: error: %s\n' "$*" >&2; exit 1; }

detect_platform() {
    os=$(uname -s)
    arch=$(uname -m)
    case "$os/$arch" in
        Darwin/arm64) echo darwin-arm64 ;;
        Linux/x86_64) echo linux-x86_64 ;;
        *) die "unsupported platform $os/$arch (agent-lab targets Apple Silicon Macs)" ;;
    esac
}

# toml_get SECTION KEY: print the string value of KEY under [SECTION] in tools.toml.
toml_get() {
    awk -v want="$1" -v key="$2" '
        /^[[:space:]]*\[/ {
            s = $0
            sub(/^[[:space:]]*\[/, "", s); sub(/\][[:space:]]*$/, "", s)
            section = s
            next
        }
        section == want {
            line = $0
            sub(/^[[:space:]]+/, "", line)
            n = index(line, "=")
            if (n == 0) next
            k = substr(line, 1, n - 1); sub(/[[:space:]]+$/, "", k)
            if (k != key) next
            v = substr(line, n + 1)
            sub(/^[[:space:]]*"/, "", v); sub(/"[[:space:]]*(#.*)?$/, "", v)
            print v
            found = 1
            exit
        }
        END { if (!found) exit 1 }
    ' "$TOOLS_TOML" || die "config/tools.toml: missing \"$2\" under [$1]"
}

sha256_of() {
    if command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        sha256sum "$1" | awk '{print $1}'
    fi
}

# stamp_get TOOL KEY: read a value bootstrap recorded when it installed TOOL.
stamp_get() {
    [ -f "$TOOLS/stamps/$1" ] || return 0
    sed -n "s/^$2=//p" "$TOOLS/stamps/$1"
}

install_tool() {
    name=$1
    version=$(toml_get "$name" version)
    url=$(toml_get "$name.$PLATFORM" url)
    sha256=$(toml_get "$name.$PLATFORM" sha256)
    format=$(toml_get "$name.$PLATFORM" format)
    member=$(toml_get "$name.$PLATFORM" binary)
    dest="$TOOLS/bin/$name"

    if [ -x "$dest" ] &&
        [ "$(stamp_get "$name" version)" = "$version" ] &&
        [ "$(stamp_get "$name" sha256)" = "$sha256" ] &&
        [ "$(stamp_get "$name" binary_sha256)" = "$(sha256_of "$dest")" ]; then
        say "$name $version already installed"
        return 0
    fi

    say "downloading $name $version"
    work="$TOOLS/tmp/$name"
    rm -rf "$work"
    mkdir -p "$work"
    download="$work/download"
    # -q: ignore ~/.curlrc so the download does not depend on user configuration.
    curl -q --fail --location --silent --show-error --retry 3 --output "$download" "$url" ||
        die "failed to download $name from $url"

    actual=$(sha256_of "$download")
    if [ "$actual" != "$sha256" ]; then
        rm -rf "$work"
        die "checksum mismatch for $name $version ($url)
  expected (config/tools.toml): $sha256
  actual:                       $actual
Refusing to install. If config/tools.toml was changed on purpose, fix the sha256."
    fi

    case "$format" in
        tar.gz)
            mkdir -p "$work/extract"
            tar -xzf "$download" -C "$work/extract" "$member" ||
                die "$name archive does not contain $member"
            binary="$work/extract/$member"
            ;;
        binary) binary="$download" ;;
        *) die "config/tools.toml: unknown format \"$format\" for $name.$PLATFORM" ;;
    esac

    chmod 755 "$binary"
    mkdir -p "$TOOLS/bin" "$TOOLS/stamps"
    mv -f "$binary" "$dest"
    printf 'version=%s\nsha256=%s\nbinary_sha256=%s\n' \
        "$version" "$sha256" "$(sha256_of "$dest")" > "$TOOLS/stamps/$name"
    rm -rf "$work"
    rmdir "$TOOLS/tmp" 2>/dev/null || true
    say "installed $name $version"
}

write_env() {
    mkdir -p "$TOOLS"
    tmp="$TOOLS/env.sh.tmp"
    # AGENT_LAB_HOME is single-quoted, so escape any single quotes in the path.
    home_quoted=$(printf '%s' "$ROOT" | sed "s/'/'\\\\''/g")
    cat > "$tmp" <<EOF
# Generated by bootstrap.sh; do not edit. Re-run ./bootstrap.sh after moving this directory.
# Load with: source .tools/env.sh   (or just use ./alab)
export AGENT_LAB_HOME='$home_quoted'
export UV_CACHE_DIR="\$AGENT_LAB_HOME/.tools/cache/uv"
export UV_PYTHON_INSTALL_DIR="\$AGENT_LAB_HOME/.tools/python"
export UV_PYTHON_BIN_DIR="\$AGENT_LAB_HOME/.tools/python/bin"
export UV_MANAGED_PYTHON=1
export UV_NO_CONFIG=1
export HF_HOME="\$AGENT_LAB_HOME/var/cache/huggingface"
export HF_HUB_DISABLE_TELEMETRY=1
export XDG_CACHE_HOME="\$AGENT_LAB_HOME/var/cache"
export PYTHONPYCACHEPREFIX="\$AGENT_LAB_HOME/var/cache/pycache"
case ":\$PATH:" in
    *":\$AGENT_LAB_HOME/.tools/bin:"*) ;;
    *) export PATH="\$AGENT_LAB_HOME/.tools/bin:\$AGENT_LAB_HOME/.venv/bin:\$PATH" ;;
esac
EOF
    mv -f "$tmp" "$TOOLS/env.sh"
}

PLATFORM=$(detect_platform)
cd "$ROOT"
[ -f .python-version ] || die ".python-version is missing"

install_tool uv
install_tool cloudflared

write_env
# Drop the caller's uv and Python settings so they cannot redirect installs
# (for example UV_PROJECT_ENVIRONMENT) outside this directory.
for var in $(env | sed -n 's/^\(UV_[A-Za-z0-9_]*\)=.*/\1/p'); do unset "$var"; done
unset VIRTUAL_ENV PYTHONHOME PYTHONPATH
# shellcheck source=/dev/null
. "$TOOLS/env.sh"

say "installing Python $(cat .python-version) into .tools/python"
uv python install --no-bin

say "installing dependencies into .venv (uv sync --frozen)"
uv sync --frozen

say "creating var/"
"$ROOT/.venv/bin/python" -c 'from agent_lab import paths; paths.ensure_layout()'

say "done. Next: ./alab doctor"
