"""The model registry, ``config/models.toml`` (design sections 3.2 and 8.2).

Each entry pins a Hugging Face repository to a commit and lists every file
with its size and sha256, so a download is reproducible and verifiable.
Entries are generated by ``alab models lock`` rather than typed by hand.
"""

from __future__ import annotations

import hashlib
import math
import re
import tomllib
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

from agent_lab import paths
from agent_lab.config import ConfigError, _Section, parse_size

GIB = 1024**3

_ID_RE = re.compile(r"[a-z0-9][a-z0-9._-]*")
_REPO_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*/[A-Za-z0-9][A-Za-z0-9._-]*")
_REVISION_RE = re.compile(r"[0-9a-f]{40}")
_SHA256_RE = re.compile(r"[0-9a-f]{64}")
_FILE_FIELDS = {"name", "size", "sha256"}

HEADER = """\
# Model registry (design sections 3.2 and 8.2).
#
# Generated by `alab models lock <id> --repo <owner/name>`; do not edit hashes by
# hand. `alab pull <id>` downloads exactly these files at this commit into
# var/models/<id>/ and verifies every sha256.
#
# disk_space uses binary units (1GB = 1024^3 bytes) and covers all files.
"""


@dataclass(frozen=True)
class ModelFile:
    name: str  # path relative to the repository root, with "/" separators
    size: int
    sha256: str


@dataclass(frozen=True)
class ModelEntry:
    id: str
    description: str
    repo: str
    revision: str
    disk_space: int
    files: tuple[ModelFile, ...]

    @property
    def total_size(self) -> int:
        return sum(f.size for f in self.files)


def _check_id(value: str) -> str | None:
    if _ID_RE.fullmatch(value):
        return None
    return f'"{value}" is not a valid model id (lowercase letters, digits, ".", "_", "-")'


def _check_repo(value: str) -> str | None:
    if _REPO_RE.fullmatch(value):
        return None
    return f'"{value}" is not a Hugging Face repository (expected "owner/name")'


def _check_revision(value: str) -> str | None:
    if _REVISION_RE.fullmatch(value):
        return None
    return f'"{value}" is not a full commit hash (40 lowercase hex digits)'


def _file_name_problem(name: str) -> str | None:
    path = PurePosixPath(name)
    if not name or path.is_absolute() or "\\" in name:
        return "must be a relative path"
    if any(part in ("", ".", "..") for part in name.split("/")):
        return 'must not contain empty, "." or ".." parts'
    if path.parts[0] == ".alab":
        return '".alab" is reserved for download state'
    return None


def _parse_files(where: str, value: Any, errors: list[str]) -> tuple[ModelFile, ...]:
    if not isinstance(value, list) or not value:
        errors.append(f"[{where}] files: expected a non-empty list of files")
        return ()
    files: list[ModelFile] = []
    seen: set[str] = set()
    for index, item in enumerate(value):
        label = f"[{where}] files[{index}]"
        if not isinstance(item, dict):
            errors.append(f"{label}: expected a table with name, size and sha256")
            continue
        for key in sorted(set(item) - _FILE_FIELDS):
            errors.append(f"{label} {key}: unknown field")
        name, size, sha256 = item.get("name"), item.get("size"), item.get("sha256")
        ok = True
        if not isinstance(name, str):
            errors.append(f"{label} name: missing or not a string")
            ok = False
        elif (problem := _file_name_problem(name)) is not None:
            errors.append(f"{label} name {name!r}: {problem}")
            ok = False
        elif name in seen:
            errors.append(f"{label} name {name}: listed twice")
            ok = False
        if isinstance(size, bool) or not isinstance(size, int) or size < 0:
            errors.append(f"{label} size: expected a non-negative integer, got {size!r}")
            ok = False
        if not isinstance(sha256, str) or not _SHA256_RE.fullmatch(sha256):
            errors.append(f"{label} sha256: expected 64 lowercase hex digits, got {sha256!r}")
            ok = False
        if ok:
            assert isinstance(name, str) and isinstance(size, int) and isinstance(sha256, str)
            seen.add(name)
            files.append(ModelFile(name=name, size=size, sha256=sha256))
    return tuple(files)


def parse_registry(path: Path, data: dict[str, Any]) -> dict[str, ModelEntry]:
    """Validate parsed TOML; raises ConfigError naming the file and every bad field."""
    errors: list[str] = []
    for key in sorted(set(data) - {"model"}):
        errors.append(f"unknown top-level key {key!r} (entries are [[model]] tables)")
    raw = data.get("model", [])
    if not isinstance(raw, list):
        errors.append("model: expected [[model]] tables")
        raw = []

    entries: dict[str, ModelEntry] = {}
    for index, table in enumerate(raw):
        label = f"model {table.get('id')}" if isinstance(table, dict) else f"model #{index + 1}"
        s = _Section(label, table, errors)
        model_id = s.string("id", _check_id)
        description = s.string("description")
        repo = s.string("repo", _check_repo)
        revision = s.string("revision", _check_revision)
        disk_space = s.size("disk_space")
        s.seen.add("files")
        files = _parse_files(label, s.table.get("files"), errors) if s.valid else ()
        s.finish()
        if model_id in entries:
            errors.append(f"[{label}] id: listed twice")
            continue
        entry = ModelEntry(model_id, description, repo, revision, disk_space, files)
        if files and disk_space and disk_space < entry.total_size:
            errors.append(
                f"[{label}] disk_space: {format_size(disk_space)} is less than the files' "
                f"total size ({entry.total_size} bytes)"
            )
        if model_id:
            entries[model_id] = entry

    if errors:
        details = "\n".join(f"  - {e}" for e in errors)
        raise ConfigError(f"invalid model registry {path}:\n{details}")
    return entries


def load_registry(path: Path | None = None) -> dict[str, ModelEntry]:
    path = path or paths.models_toml()
    try:
        with path.open("rb") as f:
            data = tomllib.load(f)
    except tomllib.TOMLDecodeError as exc:
        raise ConfigError(f"cannot parse {path}: {exc}") from exc
    except OSError as exc:
        raise ConfigError(f"cannot read {path}: {exc}") from exc
    return parse_registry(path, data)


def get_entry(model_id: str, path: Path | None = None) -> ModelEntry:
    registry = load_registry(path)
    if model_id not in registry:
        known = ", ".join(sorted(registry)) or "none"
        raise ConfigError(f'model "{model_id}" is not in the registry (known: {known})')
    return registry[model_id]


def format_size(size: int) -> str:
    """Bytes as a human-readable binary-unit size, e.g. ``"15.0GB"`` (1GB = 1024**3 bytes)."""
    if size >= GIB:
        return f"{size / GIB:.1f}GB"
    if size >= 1024**2:
        return f"{size / 1024**2:.1f}MB"
    if size >= 1024:
        return f"{size / 1024:.1f}KB"
    return f"{size}B"


def disk_space_for(total: int) -> str:
    """``total`` rounded up to the next 0.1GB, as stored in the registry."""
    tenths = max(1, math.ceil(total * 10 / GIB))
    text = f"{tenths / 10:.1f}GB"
    # Guard against float rounding putting the parsed value a few bytes below the total.
    while parse_size(text) < total:
        tenths += 1
        text = f"{tenths / 10:.1f}GB"
    return text


def _toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_entry(entry: ModelEntry) -> str:
    """One ``[[model]]`` table, in the layout ``config/models.toml`` uses."""
    lines = [
        "[[model]]",
        f"id = {_toml_string(entry.id)}",
        f"description = {_toml_string(entry.description)}",
        f"repo = {_toml_string(entry.repo)}",
        f"revision = {_toml_string(entry.revision)}",
        f"disk_space = {_toml_string(disk_space_for(entry.total_size))}",
        "files = [",
    ]
    for f in entry.files:
        lines.append(
            f"  {{ name = {_toml_string(f.name)}, size = {f.size}, "
            f"sha256 = {_toml_string(f.sha256)} }},"
        )
    lines.append("]")
    return "\n".join(lines) + "\n"


def write_entry(entry: ModelEntry, path: Path | None = None) -> None:
    """Add ``entry`` to the registry file, replacing an entry with the same id.

    Every entry is rewritten in the generated layout, in id order; the
    resulting file is parsed again before it replaces the old one.
    """
    path = path or paths.models_toml()
    registry = load_registry(path) if path.exists() else {}
    registry[entry.id] = entry
    text = HEADER + "".join("\n" + render_entry(registry[k]) for k in sorted(registry))
    parse_registry(path, tomllib.loads(text))
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text)
    tmp.replace(path)


def lock_entry(model_id: str, repo: str, revision: str, description: str) -> ModelEntry:
    """Build a registry entry from Hugging Face: resolve ``revision`` to a commit and
    record every file's size and sha256.

    Git LFS files report their sha256 in the repository metadata; the remaining
    (small) files are downloaded and hashed.
    """
    from huggingface_hub import HfApi, hf_hub_url
    from huggingface_hub.utils import build_hf_headers, get_session, hf_raise_for_status

    for problem in (_check_id(model_id), _check_repo(repo)):
        if problem:
            raise ConfigError(problem)
    info = HfApi().model_info(repo, revision=revision, files_metadata=True)
    commit = info.sha
    if commit is None or _check_revision(commit):
        raise ConfigError(f"Hugging Face returned no commit hash for {repo}@{revision}")
    files = []
    session = get_session()
    for sibling in sorted(info.siblings or [], key=lambda s: s.rfilename):
        name = sibling.rfilename
        if problem := _file_name_problem(name):
            raise ConfigError(f"{repo}: file {name!r} {problem}")
        if sibling.lfs is not None:
            size, sha256 = sibling.lfs.size, sibling.lfs.sha256
        else:
            url = hf_hub_url(repo, name, revision=commit)
            response = session.get(url, headers=build_hf_headers(), timeout=60)
            hf_raise_for_status(response)
            content = response.content
            size, sha256 = len(content), hashlib.sha256(content).hexdigest()
        if sibling.size is not None and sibling.size != size:
            raise ConfigError(f"{repo}: {name} is {size} bytes, metadata says {sibling.size}")
        files.append(ModelFile(name=name, size=size, sha256=sha256))
    if not files:
        raise ConfigError(f"{repo}@{commit} has no files")
    entry = ModelEntry(model_id, description, repo, commit, 0, tuple(files))
    return ModelEntry(
        model_id,
        description,
        repo,
        commit,
        parse_size(disk_space_for(entry.total_size)),
        tuple(files),
    )
